"""initial schema

Revision ID: c2a096a8521f
Revises: 
Create Date: 2026-02-24 21:24:39.806400

"""
from alembic import op
import sqlalchemy as sa


revision = 'c2a096a8521f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_definitions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_definitions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'OK', 'WARN', 'KO', name='dv_status'), nullable=True),
    sa.Column('raw_path', sa.Text(), nullable=True),
    sa.Column('curated_path', sa.Text(), nullable=True),
    sa.Column('dq_report_path', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('total_balance', sa.Float(), nullable=True),
    sa.Column('dq_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_definition_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.JSON(), nullable=True),
    sa.Column('curves_path', sa.Text(), nullable=True),
    sa.Column('summary_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='mv_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['model_definition_id'], ['model_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scenario_definition_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='run_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['scenario_definition_id'], ['scenario_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_artifacts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scenario_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('artifact_type', sa.Enum('cashflows', 'excel', 'metrics', 'plots', 'curves', name='artifact_type'), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('summary_metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_artifacts')
    op.drop_table('scenario_runs')
    op.drop_table('model_versions')
    op.drop_table('dataset_versions')
    op.drop_table('scenario_definitions')
    op.drop_table('model_definitions')
    op.drop_table('entities')
    # ### end Alembic commands ###
